voltzone/catalog/urls.py
from django.urls import path, re_path

import catalog.views


app_name = "catalog"

urlpatterns = [
    path("", catalog.views.product_list, name="list"),
    path(
        "category/<slug:category_slug>/",
        catalog.views.product_categories,
        name="list-category",
    ),
    re_path(
        r"^(?P<product_id>\d+)/$",
        catalog.views.product_detail,
        name="detail",
    ),
]

voltzone/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = (
    [
        path("", include("pages.urls")),
        path("catalog/", include("catalog.urls")),
        path("admin/", admin.site.urls),
        path("vacancies/", include("vacancies.urls")),
        path("summernote/", include("django_summernote.urls")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

voltzone/pages/urls.py
from django.urls import path

from pages.views import about, homepage


app_name = "pages"

urlpatterns = [
    path("", homepage, name="home"),
    path("about/", about, name="about"),
]

voltzone/vacancies/urls.py
import vacancies.views
from django.urls import path, re_path


app_name = "vacancies"

urlpatterns = [
    path("", vacancies.views.vacancies_list, name="list"),
    re_path(
        r"^(?P<vacancy_id>\d+)/$",
        vacancies.views.vacancy_detail,
        name="detail",
    ),
]

voltzone/catalog/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name="название")
    slug = models.SlugField(max_length=50, verbose_name="слаг")

    class Meta:
        verbose_name = "категория"
        verbose_name_plural = "категории"

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name="название")
    description = models.TextField(verbose_name="описание")
    count = models.PositiveIntegerField(verbose_name="количество")
    price = models.PositiveIntegerField(verbose_name="цена")
    image = models.ImageField(verbose_name="фото")
    slug = models.SlugField(max_length=100, verbose_name="слаг")

    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, verbose_name="категория"
    )

    class Meta:
        verbose_name = "товар"
        verbose_name_plural = "товары"

    def __str__(self):
        return self.name

voltzone/vacancies/models.py
from django.db import models


class Vacancy(models.Model):
    title = models.CharField(max_length=100, verbose_name="название вакансии")
    short_description = models.TextField(
        max_length=100, verbose_name="краткое описание"
    )
    description = models.TextField(verbose_name="описание")
    is_active = models.BooleanField(default=True, verbose_name="активна")
    minimal_salary = models.PositiveIntegerField(
        verbose_name="зарплат от", null=True
    )
    created_at = models.DateTimeField(
        auto_now=True, verbose_name="дата создания"
    )

    class Meta:
        verbose_name = "вакансия"
        verbose_name_plural = "вакансии"

    def __str__(self):
        return self.title

voltzone/catalog/views.py
import django.shortcuts

from catalog.models import Category, Product


def product_list(request):
    products = Product.objects.all()
    categories = Category.objects.all()
    context = {"categories": categories, "products": products}
    return django.shortcuts.render(
        request,
        "catalog/product_list.html",
        context,
    )


def product_categories(request, category_slug):
    category = django.shortcuts.get_object_or_404(Category, slug=category_slug)
    categories = Category.objects.all()
    products = Product.objects.filter(category=category).order_by("price")
    context = {
        "category": category,
        "categories": categories,
        "products": products,
    }
    return django.shortcuts.render(
        request,
        "catalog/product_list.html",
        context,
    )


def product_detail(request, product_id):
    product = django.shortcuts.get_object_or_404(Product, pk=product_id)
    context = {"product": product}
    return django.shortcuts.render(request, "catalog/product.html", context)

voltzone/pages/views.py
from django.shortcuts import render


def homepage(request):
    return render(request, "pages/home.html")


def about(request):
    return render(request, "pages/about.html")

voltzone/vacancies/views.py
import django.shortcuts
from vacancies.models import Vacancy


def vacancies_list(request):
    vacancies = Vacancy.objects.filter(is_active=True)
    context = {
        "vacancies": vacancies,
    }
    return django.shortcuts.render(
        request, "vacancies/vacancies_list.html", context
    )


def vacancy_detail(request, vacancy_id):
    vacancy = django.shortcuts.get_object_or_404(Vacancy, pk=vacancy_id)
    context = {"vacancy": vacancy}
    return django.shortcuts.render(request, "vacancies/vacancy.html", context)

voltzone/templates/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Volt Zone</title>
  <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
  {% include 'components/header.html' %}
  <main class="content">
    {% block content %}{% endblock %}
  </main>
  {% include 'components/footer.html' %}
</body>

</html>

voltzone/templates/catalog/product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="product">
    <h1 class="visually-hidden">Информация о продукте</h1>
    <div class="product-info">
      <img class="product-image" src="{{ product.image.url }}" alt="Монтажный провод" loading="lazy">
      <div class="product-details">
        <h2 class="product-header">{{ product.name }}</h2>
        <div class="product-details">
          <p class="product-price">{{ product.price }} ₽</p>
          <p class="product-stock">В наличии: {{ product.count }}</p>
          <button class="product-cart cart text-cart" type="button">
            <img src="{% static 'icons/cart.svg' %}" alt="Корзина" class="product-cart-image cart-image">
            <span class="cart-text">В корзину</span>
          </button>
        </div>
      </div>
    </div>
    <div class="product-description">
      <h3>Описание</h2>
        <p class="product-description-text">{{ product.description|safe }}</p>
    </div>
  </section>
{% endblock %}

voltzone/templates/catalog/product_list.html
{% extends 'base.html' %}
{% block content %}
  <section class="catalog">
    <div class="catalog-header">
      <h1 class="visually-hidden">Каталог</h1>
      <h2 class="catalog-title">{{ category }}</h2>
      {% if categories.count > 0 %}
        <nav class="catalog-menu">
          <ul class="catalog-menu-list menu-list">
            <li class="catalog-menu-item">
              <a href="{% url 'catalog:list' %}" class="catalog-menu-link menu-link">Все</a>
            </li>
            {% for category in categories %}
            <li class="catalog-menu-item">
              <a href="{% url 'catalog:list-category' category.slug %}"
                class="catalog-menu-link menu-link">{{ category.name }}</a>
            </li>
            {% endfor %}
          </ul>
        </nav>
      {% endif %}
    </div>
    {% if products.count > 0 %}
      <div class="catalog-grid">
        {% for product in products %}
        {% include "components/card.html" with product=product %}
        {% endfor %}
      </div>
    {% else %}
      <div class="catalog-empty">
        <p class="catalog-empty-text">В этой категории еще нет товаров (</p>
      </div>
    {% endif %}
  </section>
{% endblock %}

voltzone/templates/components/card.html
{% load static %}

<article class="catalog-card">
  <a href="{% url 'catalog:detail' product.id %}" class="catalog-card-link">
    <img src="{{ product.image.url }}" alt="Монтажный провод" class="catalog-card-image" width="300">
    <h3 class="catalog-card-title">{{ product.name }}</h3>
    <p class="catalog-card-price">{{ product.price }} ₽</p>
    {% if product.count > 19  %}
      <p class="catalog-card-stock in-stock">Много</p>
    {% elif product.count > 1 %}
      <p class="catalog-card-stock low-stock">Немного</p>
    {% elif product.count == 0 %}
      <p class="catalog-card-stock out-of-stock">Закончились</p>
    {% endif %}
  </a>
  <button class="catalog-card-cart cart" type="button">
    <img src="{% static 'icons/cart.svg' %}" alt="Корзина" class="catalog-cart-image cart-image">
  </button>
</article>

voltzone/templates/components/footer.html
<footer class="footer">
  <p class="footer-copyright">&copy; {% now "Y" %}. ООО VoltZone</p>
</footer>

voltzone/templates/components/header.html
<header class="header">
  <a href="{% url 'pages:home' %}" class="header-logo">VoltZone</a>
  <nav class="header-menu">
    <ul class="header-menu-list menu-list">
      <li class="header-menu-item">
        <a href="{% url 'pages:home' %}" class="header-menu-link menu-link">Главная</a>
      </li>
      <li class="header-menu-item">
        <a href="{% url 'catalog:list' %}" class="header-menu-link menu-link">Каталог</a>
      </li>
      <li class="header-menu-item">
        <a href="{% url 'vacancies:list' %}" class="header-menu-link menu-link">Вакансии</a>
      </li>
      <li class="header-menu-item">
        <a href="{% url 'pages:about' %}" class="header-menu-link menu-link">О нас</a>
      </li>
      {% if request.user.is_staff %}
        <li class="header-menu-item">
          <a href="{% url 'admin:index' %}" class="header-menu-link menu-link">Админка</a>
        </li>
      {% endif %}
    </ul>
  </nav>
</header>

voltzone/templates/pages/about.html
{% extends 'base.html' %}
{% block content %}
  <section class="about">
    <h1 class="about-title">О нас</h1>
    <div class="about-content">
      <p class="about-description">
        Мы — не просто магазин электроники, а сообщество единомышленников, горящих страстью к технологиям и инновациям.
        Наша история началась в 2015 году, когда группа инженеров-энтузиастов решила создать пространство, где сложные
        электронные компоненты становятся доступными инструментами для творчества. За эти годы мы выросли из небольшой
        мастерской в крупный центр технологических решений, но сохранили главное — искреннюю веру в то, что технологии
        должны быть понятными, вдохновляющими и открытыми для всех. Сегодня мы объединяем более 50 000 изобретателей,
        студентов и профессионалов по всей стране, помогая превращать смелые идеи в работающие прототипы и готовые
        продукты.
      </p>
      <div class="about-map-container">
        <div style="position:relative;overflow:hidden;"><a
            href="https://yandex.ru/maps/213/moscow/?utm_medium=mapframe&utm_source=maps"
            style="color:#eee;font-size:12px;position:absolute;top:0px;">Москва</a><a
            href="https://yandex.ru/maps/213/moscow/house/gogolevskiy_bulvar_29/Z04Ycw5pT00AQFtvfXt1eHpnZw==/?ll=37.601206%2C55.749864&utm_medium=mapframe&utm_source=maps&z=17.82"
            style="color:#eee;font-size:12px;position:absolute;top:14px;">Гоголевский бульвар, 29 —
            Яндекс Карты</a><iframe class="about-map"
            src="https://yandex.ru/map-widget/v1/?ll=37.601206%2C55.749864&mode=whatshere&whatshere%5Bpoint%5D=37.599346%2C55.749464&whatshere%5Bzoom%5D=17&z=17.82"
            frameborder="1" allowfullscreen="true" style="position:relative;"></iframe>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

voltzone/templates/pages/home.html
{% extends 'base.html' %}
{% block content %}
  <section class="banner">
    <h1 class="banner-title">VoltZone</h1>
    <p class="banner-text">Здесь техника — не просто приборы, а добрые помощники в вашем доме.</p>
  </section>
{% endblock %}

voltzone/templates/vacancies/vacancies_list.html
{% extends 'base.html' %}
{% block content %}
<section class="vacancies">
  {% if vacancies.count > 0 %}
    {% for vacancy in vacancies %}
      <article class="vacancies-card">
        <a href="{% url 'vacancies:detail' vacancy.id %}" class="vacancies-card-link">
          <h3 class="vacancies-card-title">{{ vacancy.title }}</h3>
          <p class="vacancies-card-minimal-salary">От {{ vacancy.minimal_salary }} ₽ за месяц, на руки</p>
          <p class="vacancies-card-short-description">{{ vacancy.short_description }}</p>
        </a>
        <a class="vacancies-card-contacts">Контакты</a>
      </article>
    {% endfor %}
  {% else %}
    <p class="vacancies-empty-text">Ожидайте, скоро добавим вакансии</p>
  {% endif %}  
</section>
{% endblock %}

voltzone/templates/vacancies/vacancy.html
{% extends 'base.html' %}
{% block content %}
<section class="vacancy-details">
  <h3 class="vacancy-card-title">{{ vacancy.title }}</h3>
  <p class="vacancy-card-minimal-salary">от {{ vacancy.minimal_salary }} ₽ за месяц, на руки</p>
  <p class="vacancy-card-description">{{ vacancy.description|safe }}</p>
  <a class="vacancy-card-response">Откликнуться</a>
</section>
{% endblock %}